---
galaxy_info:
  role_name: ivanti_incident
  author: Mark Lowcher (@mlowcher61)
  description: Manage Ivanti Neurons for ITSM / Service Manager incidents via the ivanti_incident module.
  license: MIT
  min_ansible_version: "2.16"
  galaxy_tags:
    - ivanti
    - itsm
    - incident
    - automation
dependencies: []
